<?php /** @var \ParadoxLabs\Subscriptions\Block\Customer\Edit\Billing $block */ ?>
<?php /* @codingStandardsIgnoreFile */ ?>

<div class="fieldset billing-address">
    <?php $addresses = $block->getCustomer()->getAddresses(); ?>
    <?php $subscriptionAddress = $block->getSubscription()->getQuote()->getBillingAddress(); ?>
    <?php if (!empty($addresses)): ?>
        <div class="field billing-address-id do-not-toggle required">
            <label class="label" for="billing_address_id"><span><?= $block->escapeHtml(__('Billing Address')) ?></span></label>
            <div class="control">
                <select id="billing_address_id" name="billing[address_id]" title="<?= $block->escapeHtmlAttr(__('Billing Address')) ?>" class="control-select">
                    <option value=""><?= $block->escapeHtml(__('Enter below')) ?></option>
                    <?php /** @var \Magento\Customer\Api\Data\AddressInterface $address  */ ?>
                    <?php foreach ($addresses as $address): ?>
                        <option value="<?= (int)$address->getId(); ?>"<?php if ($this->helper(\ParadoxLabs\TokenBase\Helper\Address::class)->compareAddresses($address, $subscriptionAddress)): ?> selected="selected"<?php endif; ?>><?= $block->escapeHtml($block->getFormattedAddress($address, 'flat')); ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>
    <?php endif; ?>
    <?= $block->getNameBlockHtml() ?>
    <div class="field company">
        <label class="label" for="billing_company"><span><?= $block->escapeHtml(__('Company')) ?></span></label>
        <div class="control">
            <input type="text" name="billing[company]" id="billing_company" title="<?= $block->escapeHtmlAttr(__('Company')) ?>" value="<?= $block->escapeHtmlAttr($block->getAddress()->getCompany()) ?>" class="input-text <?= $block->escapeHtmlAttr($this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('company')) ?>">
        </div>
    </div>
    <?php $phoneValidation = $this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('telephone'); ?>
    <div class="field telephone<?php if (strpos($phoneValidation, 'required') !== false): ?> required<?php endif; ?>">
        <label class="label" for="billing_telephone"><span><?= $block->escapeHtml(__('Phone Number')) ?></span></label>
        <div class="control">
            <input type="text" name="billing[telephone]" value="<?= $block->escapeHtmlAttr($block->getAddress()->getTelephone()) ?>" title="<?= $block->escapeHtmlAttr(__('Phone Number')) ?>" class="input-text <?= $block->escapeHtmlAttr($phoneValidation) ?>" id="billing_telephone">
        </div>
    </div>
    <div class="field fax">
        <label class="label" for="billing_fax"><span><?= $block->escapeHtml(__('Fax')) ?></span></label>
        <div class="control">
            <input type="text" name="billing[fax]" id="billing_fax" title="<?= $block->escapeHtmlAttr(__('Fax')) ?>" value="<?= $block->escapeHtmlAttr($block->getAddress()->getFax()) ?>" class="input-text <?= $block->escapeHtmlAttr($this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('fax')) ?>">
        </div>
    </div>
    <?php $_streetValidationClass = $block->escapeHtmlAttr($this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('street')); ?>
    <div class="field street required">
        <label for="billing_street_1" class="label"><span><?= $block->escapeHtml(__('Street Address')) ?></span></label>
        <div class="control">
            <input type="text" name="billing[street][]" value="<?= $block->escapeHtmlAttr($block->getStreetLine(1)) ?>" title="<?= $block->escapeHtmlAttr(__('Street Address')) ?>" id="billing_street_1" class="input-text <?= $_streetValidationClass ?>"  />
            <div class="nested">
                <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                <?php for ($_i = 1, $_n = $this->helper(\Magento\Customer\Helper\Address::class)->getStreetLines(); $_i < $_n; $_i++): ?>
                    <?php $lineNo = ($_i+1); ?>
                    <div class="field additional">
                        <label class="label" for="billing_street_<?= $lineNo ?>">
                            <span><?= $block->escapeHtml(__('Street Address %1', $lineNo)) ?></span>
                        </label>
                        <div class="control">
                            <input type="text" name="billing[street][]" value="<?= $block->escapeHtmlAttr($block->getStreetLine($lineNo)) ?>" title="<?= $block->escapeHtmlAttr(__('Street Address %1', $lineNo)) ?>" id="billing_street_<?= $lineNo ?>" class="input-text <?= $_streetValidationClass ?>">
                        </div>
                    </div>
                <?php endfor; ?>
            </div>
        </div>
    </div>

    <?php if ($this->helper(\Magento\Customer\Helper\Address::class)->isVatAttributeVisible()) : ?>
        <div class="field taxvat">
            <label class="label" for="billing_vat_id"><span><?= $block->escapeHtml(__('VAT Number')) ?></span></label>
            <div class="control">
                <input type="text" name="billing[vat_id]" value="<?= $block->escapeHtmlAttr($block->getAddress()->getVatId()) ?>" title="<?= $block->escapeHtmlAttr(__('VAT Number')) ?>" class="input-text <?= $block->escapeHtmlAttr($this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('vat_id')) ?>" id="billing_vat_id">
            </div>
        </div>
    <?php endif; ?>
    <div class="field city required">
        <label class="label" for="billing_city"><span><?= $block->escapeHtml(__('City')) ?></span></label>
        <div class="control">
            <input type="text" name="billing[city]" value="<?= $block->escapeHtmlAttr($block->getAddress()->getCity()) ?>" title="<?= $block->escapeHtmlAttr(__('City')) ?>" class="input-text <?= $block->escapeHtmlAttr($this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('city')) ?>" id="billing_city">
        </div>
    </div>
    <div class="field region required">
        <label class="label" for="billing_region_id"><span><?= $block->escapeHtml(__('State/Province')) ?></span></label>
        <div class="control">
            <select id="billing_region_id" name="billing[region_id]" title="<?= $block->escapeHtmlAttr(__('State/Province')) ?>" class="validate-select" <?=(!$block->getConfig('general/region/display_all')) ? ' disabled="disabled"' : '';?>>
                <option value=""><?= $block->escapeHtml(__('Please select a region, state or province.')) ?></option>
            </select>
            <input type="text" id="billing_region" name="billing[region]" value="<?= $block->escapeHtmlAttr($block->getRegion()) ?>"  title="<?= $block->escapeHtmlAttr(__('State/Province')) ?>" class="input-text <?= $block->escapeHtmlAttr($this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('region')) ?>"<?=(!$block->getConfig('general/region/display_all')) ? ' disabled="disabled"' : '';?>/>
        </div>
    </div>
    <div class="field zip required">
        <label class="label" for="billing_zip"><span><?= $block->escapeHtml(__('Zip/Postal Code')) ?></span></label>
        <div class="control">
            <input type="text" name="billing[postcode]" value="<?= $block->escapeHtmlAttr($block->getAddress()->getPostcode()) ?>" title="<?= $block->escapeHtmlAttr(__('Zip/Postal Code')) ?>" id="billing_zip" class="input-text validate-zip-international <?= $block->escapeHtmlAttr($this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('postcode')) ?>">
        </div>
    </div>
    <div class="field country required">
        <label class="label" for="billing_country"><span><?= $block->escapeHtml(__('Country')) ?></span></label>
        <div class="control">
            <?= $block->getCountryHtmlSelect(null, 'billing[country_id]', 'billing_country') ?>
        </div>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "#billing_country": {
            "regionUpdater": {
                "optionalRegionAllowed": <?= $block->getConfig('general/region/display_all') ? 'true' : 'false' ?>,
                "regionListId": "#billing_region_id",
                "regionInputId": "#billing_region",
                "postcodeId": "#billing_zip",
                "form": "#form-validate",
                "regionJson": <?= $this->helper(\Magento\Directory\Helper\Data::class)->getRegionJson() ?>,
                "defaultRegion": "<?= (int)$block->getRegionId() ?>",
                "countriesWithOptionalZip": <?= $this->helper(\Magento\Directory\Helper\Data::class)->getCountriesWithOptionalZip(true) ?>
            }
        }
    }
</script>
