<?php
/** @var \ParadoxLabs\Subscriptions\Block\Adminhtml\Subscription\View\Tab\Shipping $block */
// @codingStandardsIgnoreFile
?>
<fieldset class="fieldset admin__fieldset" id="subscription_fieldset_shipping" data-mage-init='{"subscriptionsAddressFields":{"addressSelector":"#shipping_address_id"}}'>
    <legend class="admin__legend legend">
        <span><?= $block->escapeHtml(__('Shipping Information')); ?></span>
    </legend><br />
    <?php if ((bool)$block->getSubscription()->getQuote()->getIsVirtual() === true): ?>
        <div class="admin__field field field-is_virtual no-label" data-ui-id="subscription-edit-form-fieldset-element-form-field-is-virtual">
            <div id="subscription_is_virtual" class="control-value admin__field-value">
                <?= $block->escapeHtml(__("This subscription is virtual, so there's no need to set a shipping address.")); ?>
            </div>
        </div>
    <?php else: ?>
        <?php $shippingMethods = $block->getShippingMethods(); ?>
        <?php $shippingMethodValid = $block->isValidShippingMethod(); ?>
        <?php if ($shippingMethodValid !== true): ?>
            <div class="admin__field field field-shipping_method_error no-label" data-ui-id="subscription-edit-form-fieldset-element-form-field-shipping-method-error">
                <div id="subscription_shipping_method_error" class="control-value admin__field-value message message-error">
                    <?= $block->escapeHtml(__('This subscription does not have a valid shipping method assigned. Please choose a shipping method below and save to prevent interruption.')); ?>
                </div>
            </div>
        <?php endif; ?>
        <div class="admin__field region <?php if (!empty($shippingMethods)): ?>_required<?php endif; ?>">
            <label class="admin__field-label" for="shipping_method"><span><?= $block->escapeHtml(__('Shipping Method')) ?></span></label>
            <div class="admin__field-control">
                <select id="shipping_method" name="shipping[method]" title="<?= $block->escapeHtmlAttr(__('Shipping Method')) ?>" class="admin__control-select" <?php if (!empty($shippingMethods)): ?>data-validate='{required:true}'<?php endif; ?>>
                    <?php if ($shippingMethodValid !== true): ?>
                        <option value="<?= $block->getSubscription()->getQuote()->getShippingAddress()->getOrigData('shipping_method'); ?>"><?= __('ASSIGNED: %1', $block->getSubscription()->getQuote()->getShippingAddress()->getOrigData('shipping_description')); ?></option>
                    <?php endif; ?>
                    <?php foreach ($shippingMethods as $methods): ?>
                        <?php /** @var \Magento\Quote\Model\Quote\Address\Rate $method */ ?>
                        <?php foreach ($methods as $method): ?>
                            <option value="<?= $method->getCode(); ?>"<?php if ($method->getCode() === $block->getSubscription()->getQuote()->getShippingAddress()->getShippingMethod()): ?> selected="selected"<?php endif; ?>>
                                <?= $block->escapeHtml(__('%1 - %2 (%3)', $method->getCarrierTitle(), $method->getMethodTitle(), $block->getShippingMethodPrice($method->getPrice()))); ?>
                            </option>
                        <?php endforeach; ?>
                    <?php endforeach; ?>
                </select>
                <div class="note admin__field-note" id="shipping_method-note"><?= $block->escapeHtml(__('Rate costs are estimated, and may vary over time.')); ?></div>
            </div>
        </div>
        <?php $addresses = $block->getCustomer()->getAddresses(); ?>
        <?php $subscriptionAddress = $block->getSubscription()->getQuote()->getShippingAddress(); ?>
        <?php if (!empty($addresses)): ?>
            <div class="admin__field region _required">
                <label class="admin__field-label" for="shipping_address_id"><span><?= $block->escapeHtml(__('Shipping Address')) ?></span></label>
                <div class="admin__field-control">
                    <select id="shipping_address_id" name="shipping[address_id]" title="<?= $block->escapeHtmlAttr(__('Shipping Address')) ?>" class="admin__control-select">
                        <option value=""><?= $block->escapeHtml(__('Enter below')) ?></option>
                        <?php /** @var \Magento\Customer\Api\Data\AddressInterface $address  */ ?>
                        <?php foreach ($addresses as $address): ?>
                            <option value="<?= (int)$address->getId(); ?>"<?php if ($this->helper(\ParadoxLabs\TokenBase\Helper\Address::class)->compareAddresses($address, $subscriptionAddress)): ?> selected="selected"<?php endif; ?>><?= $block->escapeHtml($block->getFormattedAddress($address, 'flat')); ?></option>
                        <?php endforeach; ?>
                    </select>
                    <div class="note admin__field-note" id="shipping_method-note"><?= $block->escapeHtml(__('Available shipping methods may change after saving an address change.')); ?></div>
                </div>
            </div>
        <?php endif; ?>
        <div class="admin__field toggle field-name-firstname _required">
            <label class="admin__field-label" for="firstname"><span><?= $block->escapeHtml(__('First Name')) ?></span></label>
            <div class="admin__field-control">
                <input type="text" name="shipping[firstname]" id="firstname" title="<?= $block->escapeHtmlAttr(__('First Name')) ?>" value="<?= $block->escapeHtmlAttr($block->getAddress()->getFirstname()) ?>" class="admin__control-text <?= $block->escapeHtmlAttr($this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('firstname')) ?>" data-validate='{required:true}'>
            </div>
        </div>
        <div class="admin__field toggle field-name-lastname _required">
            <label class="admin__field-label" for="lastname"><span><?= $block->escapeHtml(__('Last Name')) ?></span></label>
            <div class="admin__field-control">
                <input type="text" name="shipping[lastname]" id="lastname" title="<?= $block->escapeHtmlAttr(__('Last Name')) ?>" value="<?= $block->escapeHtmlAttr($block->getAddress()->getLastname()) ?>" class="admin__control-text <?= $block->escapeHtmlAttr($this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('lastname')) ?>" data-validate='{required:true}'>
            </div>
        </div>
        <div class="admin__field toggle company">
            <label class="admin__field-label" for="company"><span><?= $block->escapeHtml(__('Company')) ?></span></label>
            <div class="admin__field-control">
                <input type="text" name="shipping[company]" id="company" title="<?= $block->escapeHtmlAttr(__('Company')) ?>" value="<?= $block->escapeHtmlAttr($block->getAddress()->getCompany()) ?>" class="admin__control-text <?= $block->escapeHtmlAttr($this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('company')) ?>">
            </div>
        </div>
        <?php $phoneValidation = $this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('telephone'); ?>
        <div class="admin__field toggle telephone<?php if (strpos($phoneValidation, 'required') !== false): ?> _required<?php endif; ?>">
            <label class="admin__field-label" for="telephone"><span><?= $block->escapeHtml(__('Phone Number')) ?></span></label>
            <div class="admin__field-control">
                <input type="text" name="shipping[telephone]" value="<?= $block->escapeHtmlAttr($block->getAddress()->getTelephone()) ?>" title="<?= $block->escapeHtmlAttr(__('Phone Number')) ?>" class="admin__control-text <?= $block->escapeHtmlAttr($phoneValidation) ?>" id="telephone"<?php if (strpos($phoneValidation, 'required') !== false): ?> data-validate='{required:true}'<?php endif; ?>>
            </div>
        </div>
        <?php $faxValidation = $this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('fax'); ?>
        <div class="admin__field toggle fax<?php if (strpos($faxValidation, 'required') !== false): ?> _required<?php endif; ?>">
            <label class="admin__field-label" for="fax"><span><?= $block->escapeHtml(__('Fax Number')) ?></span></label>
            <div class="admin__field-control">
                <input type="text" name="shipping[fax]" value="<?= $block->escapeHtmlAttr($block->getAddress()->getFax()) ?>" title="<?= $block->escapeHtmlAttr(__('Fax Number')) ?>" class="admin__control-text <?= $block->escapeHtmlAttr($faxValidation) ?>" id="fax"<?php if (strpos($faxValidation, 'required') !== false): ?> data-validate='{required:true}'<?php endif; ?>>
            </div>
        </div>
        <?php $_streetValidationClass = $block->escapeHtmlAttr($this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('street')); ?>
        <div class="admin__field toggle street _required">
            <label for="street" class="admin__field-label"><span><?= $block->escapeHtml(__('Street')) ?></span></label>
            <div class="admin__field-control">
                <input type="text" name="shipping[street][]" value="<?= $block->escapeHtmlAttr($block->getStreetLine(1)) ?>" title="<?= $block->escapeHtmlAttr(__('Street Address')) ?>" id="street" class="admin__control-text <?= $_streetValidationClass ?>" data-validate='{required:true}' />
                <div class="nested">
                    <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                    <?php for ($_i = 1, $_n = $this->helper(\Magento\Customer\Helper\Address::class)->getStreetLines(); $_i < $_n; $_i++): ?>
                        <?php $lineNo = ($_i+1); ?>
                        <div class="admin__field additional">
                            <div class="admin__field-control">
                                <input type="text" name="shipping[street][]" value="<?= $block->escapeHtmlAttr($block->getStreetLine($lineNo)) ?>" title="<?= $block->escapeHtmlAttr(__('Street Address %1', $lineNo)) ?>" id="street_<?= $lineNo ?>" class="admin__control-text <?= $_streetValidationClass ?>">
                            </div>
                        </div>
                    <?php endfor; ?>
                </div>
            </div>
        </div>
        <div class="admin__field toggle city _required">
            <label class="admin__field-label" for="city"><span><?= $block->escapeHtml(__('City')) ?></span></label>
            <div class="admin__field-control">
                <input type="text" name="shipping[city]" value="<?= $block->escapeHtmlAttr($block->getAddress()->getCity()) ?>" title="<?= $block->escapeHtmlAttr(__('City')) ?>" class="admin__control-text <?= $block->escapeHtmlAttr($this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('city')) ?>" id="city" data-validate='{required:true}'>
            </div>
        </div>
        <div class="admin__field toggle region _required">
            <label class="admin__field-label" for="region-id"><span><?= $block->escapeHtml(__('State/Province')) ?></span></label>
            <div class="admin__field-control">
                <select id="region-id" name="shipping[region_id]" title="<?= $block->escapeHtmlAttr(__('State/Province')) ?>" class="admin__control-select validate-select" <?php echo(!$block->getConfig('general/region/display_all')) ? ' disabled="disabled"' : '';?>>
                    <option value=""><?= $block->escapeHtml(__('Please select a region, state or province.')) ?></option>
                </select>
                <input type="text" id="region" name="shipping[region]" value="<?= $block->escapeHtmlAttr($block->getAddress()->getRegion() instanceof \Magento\Customer\Api\Data\RegionInterface ? $block->getAddress()->getRegion()->getRegion() : $block->getAddress()->getRegion()) ?>"  title="<?= $block->escapeHtmlAttr(__('State/Province')) ?>" class="admin__control-text <?= $block->escapeHtmlAttr($this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('region')) ?>"<?php echo(!$block->getConfig('general/region/display_all')) ? ' disabled="disabled"' : '';?>/>
            </div>
        </div>
        <div class="admin__field toggle zip _required">
            <label class="admin__field-label" for="zip"><span><?= $block->escapeHtml(__('Zip/Postal Code')) ?></span></label>
            <div class="admin__field-control">
                <input type="text" name="shipping[postcode]" value="<?= $block->escapeHtmlAttr($block->getAddress()->getPostcode()) ?>" title="<?= $block->escapeHtmlAttr(__('Zip/Postal Code')) ?>" id="zip" class="admin__control-text validate-zip-international <?= $block->escapeHtmlAttr($this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('postcode')) ?>">
            </div>
        </div>
        <div class="admin__field toggle country _required">
            <label class="admin__field-label" for="country"><span><?= $block->escapeHtml(__('Country')) ?></span></label>
            <div class="admin__field-control">
                <?= str_replace('class="', 'class="admin__control-select ', $block->getCountryHtmlSelect($block->getAddress()->getCountryId(), 'shipping[country_id]', 'country')) ?>
            </div>
        </div>
        <script type="text/javascript">
            //<![CDATA[
            <?php /* @see Magento\Customer\Block\Adminhtml\Edit\Renderer\Region::render() */ ?>
            require(["prototype", "mage/adminhtml/form"], function(){
                jQuery("#region-id").attr("defaultValue", "<?= (int)$block->getAddress()->getRegionId() ?>");
                new RegionUpdater("country", "region", "region-id", <?= $this->helper(\Magento\Directory\Helper\Data::class)->getRegionJson() ?> );
            });
            //]]>
        </script>
    <?php endif; ?>
</fieldset>
