<?php
/**
 * @var $block \Ssmd\CustomerNotes\Block\Adminhtml\Customer\CustomerNotes
 */

//echo $this->getUrl('customernotes'); exit;.
//echo $block->getAdminUserId(); exit;
?>

<div class="fieldset-wrapper customer-information">

    <div>
        <form method="post" name="add_note" id="add_note" data-mage-init='{"validation": {}}'>
            <fieldset class="fieldset">
                <legend class="legend"><span><?= $block->escapeHtmlAttr(__('Store Credit')) ?></span>&nbsp;</legend>
                <div class="fields col-md-6">
                    <div class="field form_key">
                        <div class="control">
                            <input type="hidden" name="form_key" id="form_key" value="<?= $block->getFormKey() ?>" />
                        </div>
                    </div>
                </div>
                <div class="fields col-md-6">
                    <div class="field admin_user_id">
                        <div class="control">
                            <input type="hidden" name="admin_user_id" id="admin_user_id" value="<?= $block->getAdminUserId() ?>" />
                        </div>
                    </div>
                </div>
                <div class="fields col-md-6">
                    <div class="field mage_customer_id">
                        <div class="control">
                            <input type="hidden" name="mage_customer_id" id="mage_customer_id" value="<?= $block->getCustomerId() ?>" />
                        </div>
                    </div>
                </div>

                <div class="fields col-md-6">
                    <div class="field store_credit">
                        <div class="control">
                            <input type="number" name="txt_credit" id="txt_credit" data-validate="{required:true}" style="width: 415px;">
                        </div>
                    </div>
                </div>
                <br>
                <div class="fields col-md-6">
                    <div class="field store_credit">
                        <div class="control">
                            <textarea name="txt_comments" id="txt_comments" cols="50" rows="10" data-validate="{required:true}"></textarea>
                        </div>
                    </div>
                </div>

            </fieldset>
            <div class="actions-toolbar">
                <div class="primary">
                    <button type="submit" class="action submit primary" id="add_store_credit" title="Submit"><span><?= $block->
                            escapeHtmlAttr(__(' Submit ')) ?></span></button>
                </div>
            </div>
        </form>
    </div>

    <div>
        <?php $collection = $block->getStoreCreditHistory(); ?>

        <div class="row">
            <div class="credit-div col-12">
                <?php if(count($collection->getData())>0): ?>
                    <?php foreach($collection as $note): ?>

                        <div class="divider">
                            <div class="note-list-by">
                                <span ><strong>Store Credit : </strong></span>
                                <span>$<?php echo $note->getAmount() ?></span>
                                <span>&nbsp;&nbsp;</span>
                                <span>|</span>
                                <span>&nbsp;&nbsp;</span>
                                <span ><strong>By : </strong></span>
                                <span><?php echo $block->getAdminUserNameById($note->getAdminUserId()) ?></span>
                                <span>&nbsp;&nbsp;</span>
                                <span>|</span>
                                <span>&nbsp;&nbsp;</span>
                                <span><strong>On : </strong></span>
                                <span><?php echo date('jS F, Y G:i A', strtotime($note->getCreatedAt())) ?></span>
                            </div>

                            <div class="note-list-content">
                                <span><?php echo $note->getComments() ?></span>
                            </div>
                        </div>
                    <?php endforeach; ?>
                <?php endif; ?>
            </div>
        </div>
        <?php if(count($collection->getData())==0 AND $block->getM1StoreCredit() != 0): ?>

        <div>
            <span ><strong>M1 Store Credit : </strong></span>
            <span>$<?php echo $block->getM1StoreCredit() ?></span>
        </div>
        <?php endif; ?>

    </div>
</div>

<script>

    require(['jquery'], function($) {

        $(document).ready(function(){

            $('#add_store_credit').click(function(e) {

                e.preventDefault();

                var admin_user_id       = $('#admin_user_id').val();
                var mage_customer_id    = $('#mage_customer_id').val();
                var txt_credit          = $('#txt_credit').val();
                var txt_comments        = $('#txt_comments').val();

                if(txt_comments == "" || txt_comments == null || txt_credit == "" || txt_credit == null)
                {
                    alert('This is required field');
                    return false;
                }
                //alert(customer_note);
                var formKey = $("[name='form_key']").val();
                //alert(formKey);

                var url = '<?php echo $this->getUrl('storecredit') ?>';

                $.ajax({
                    url: url,
                    type: "POST",
                    data: {
                        'form_key':formKey,
                        'admin_user_id': admin_user_id,
                        'mage_customer_id':mage_customer_id,
                        'txt_credit':txt_credit,
                        'txt_comments':txt_comments
                    },
                    showLoader: true,
                    cache: false,
                    success: function (data, status, xhr) {
                        $('#txt_credit').val("");
                        $('#txt_comments').val("");
                        $('.credit-div.col-12').prepend(data);

                    },
                    error: function (jqXhr, textStatus, errorMessage) {
                        console.log('Error' + errorMessage);
                    }
                });

            });

        });
    });
</script>
<style>
    .credit-div {
        padding-top: 20px;
    }

    .credit-div .divider {
        border-bottom: 1px solid #e2e2e2;
        /*margin-bottom: 30px;*/
        padding-left: 15px;
        padding-bottom: 15px;
        padding-right: 15px;
    }

    .divider p:empty {
        display: none;
    }
    .credit-div .divider:last {
        border-bottom:none;
    }

    .credit-div h4 {
        font-weight: bold;
        margin-bottom: 0px;
        font-size: 18px;
    }

    .credit-div p#subhead {
        margin: 20px 0px;
        font-size: 12px;
    }

    .divider p {
        margin-bottom: 5px;
    }

    .note-list-by{
        padding-top: 10px;
        padding-bottom: 10px;
    }
    .note-list-content{
        padding-top: 10px;
        padding-bottom: 10px;
    }

</style>
