<?php /** @var \ParadoxLabs\Subscriptions\Block\Customer\View $block */ ?>
<?php /* @codingStandardsIgnoreFile */ ?>

<?= $block->getChildHtml('items'); ?>

<div class="block block-subscription-info">
    <div class="block-title"><strong><?= $block->escapeHtml(__('Details')); ?></strong></div>
    <div class="block-content">
        <div class="box box-address-billing">
            <strong class="box-title">
                <span><?= $block->escapeHtml(__('Bill To')); ?></span>
            </strong>
            <div class="box-content">
                <?php $card = $block->getCard(); ?>
                <?php if ($card instanceof \Magento\Vault\Api\Data\PaymentTokenInterface): ?>
                    <strong>
                        <span>
                            <?= $block->escapeHtml($block->getCardLabel($card)); ?>
                        </span>
                    </strong>
                    <?php if (!empty($block->getCardExpires($card))): ?>
                        <small><?= $block->escapeHtml(__('(Expires %1)', date('m/Y', (int)strtotime((string)$block->getCardExpires($card))))); ?></small>
                    <?php endif; ?>
                    <address>
                        <?= $block->getFormattedAddress($block->getSubscription()->getQuote()->getBillingAddress()->getDataModel()); ?>
                    </address>
                <?php else: ?>
                    <strong>
                        <span>
                            <?= $block->escapeHtml(__('No info found. Please add a payment method.')); ?>
                        </span>
                    </strong>
                <?php endif; ?>
            </div>
        </div>

        <?php if ((bool)$block->getSubscription()->getQuote()->getIsVirtual() === false): ?>
            <div class="box box-address-shipping">
                <strong class="box-title">
                    <span><?= $block->escapeHtml(__('Ship To')); ?></span>
                </strong>
                <div class="box-content">
                    <address>
                        <?= $block->getFormattedAddress($block->getSubscription()->getQuote()->getShippingAddress()->getDataModel()); ?>
                    </address>
                </div>
            </div>
        <?php endif; ?>

        <div class="box box-schedule">
            <strong class="box-title">
                <span><?= $block->escapeHtml(__('Subscription')); ?></span>
            </strong>
            <div class="box-content">
                <p class="description"><?= $block->escapeHtml($block->getSubscription()->getDescription()); ?></p>
                <dl class="item-options">
                    <?php $length = $block->getSubscription()->getLength(); ?>
                    <?php $count  = $block->getSubscription()->getRunCount(); ?>
                    <?php if ($length > 0): ?>
                        <dt><?= $block->escapeHtml(__(ucfirst((string)$block->getInstallmentLabel()))); ?></dt>
                        <dd>
                            <?= $block->escapeHtml(__('%1 of %2 completed', $count, $length)); ?>
                            <?php if ($count < $length && $block->getSubscription()->getStatus() !== \ParadoxLabs\Subscriptions\Model\Source\Status::STATUS_CANCELED): ?>
                                <?= $block->escapeHtml(__('(%1 remaining)', $length - $count)); ?>
                            <?php endif; ?>
                        </dd>
                    <?php endif; ?>
                    <dt><?= $block->escapeHtml(__('Runs every')); ?></dt>
                    <dd><?= $block->escapeHtml($block->getSubscriptionFrequencyLabel()); ?></dd>
                    <?php /*<dt><?= $block->escapeHtml(__('Started')); ?></dt>
                    <dd><?= $block->escapeHtml($block->formatDate($block->getSubscription()->getCreatedAt(), \IntlDateFormatter::MEDIUM)); ?></dd> */ ?>
                    <dt><?= $block->escapeHtml(__('Last run')); ?></dt>
                    <dd><?= $block->escapeHtml($block->formatDate($block->getSubscription()->getLastRun(), \IntlDateFormatter::MEDIUM)); ?></dd>
                    <?php if ($block->getSubscription()->getStatus() === \ParadoxLabs\Subscriptions\Model\Source\Status::STATUS_ACTIVE): ?>
                        <dt><?= $block->escapeHtml(__('Next run')); ?></dt>
                        <dd><?= $block->escapeHtml($block->formatDate($block->getSubscription()->getNextRun(), \IntlDateFormatter::MEDIUM)); ?></dd>
                    <?php endif; ?>
                </dl>
            </div>
        </div>
    </div>
</div>

<?= $this->getChildHtml('logs'); ?>
