<?php

$data = $this->getAnsweredQuestionsByUniqString($this->getUniqString());

$dividerElement = false;
?>


<?php if (count($data) > 0): ?>
<div id="ques" class="container-fuild">
    <div class="container custom-container">
        <div class="row">
            <div class="divider-div col-12">
                <?php foreach ($data

                as $groupId => $groupData):

                $displayQuestionFlag = true;
                if ($dividerElement) {
                    $dividerElement = false;
                    echo '</div>';
                }
                ?>





                <?php foreach ($groupData  as $_item):
                //print_r($_item);
                $noneClass = '';
                /*if ($_item['question_data']['question_text'] == 'Acknowledgements') {
                    continue;
                }

                if ($_item['response_type'] == 'submit' || $_item['response_type'] == 'button'){
                    continue;
                }*/
                ?>


                <?php if ($displayQuestionFlag):

                $dividerElement = true;
                ?>

                <div class="divider">

                    <div class='' id="heading">
                        <div class="">
                            <h5><?php echo $_item['question_data']['question_text']; ?></h5>

                            <?php if ($_item['question_data']['question_subtext'] != ""): ?>
                                <p id="subhead"
                                   class="font-15"><?php echo $_item['question_data']['question_subtext']; ?></p>
                            <?php endif; ?>
                        </div>
                    </div>
                    <?php endif;
                    ?>

                    <?php
                    $displayQuestionFlag = false;
                    ?>

                    <?php
                    if ($_item['response_type'] == 'radio'):
                        ?>

                        <div class="answer">
                            <div class="form-check">

                                <!-- <input type="radio" class="form-check-input" checked
                                                           readonly/><label
                                    class="form-check-label"><?php echo $_item['question_response_data']['label']; ?></label> -->
                                <label
                                    class="input-check-label"><?php echo $_item['question_response_data']['label']; ?>
                                    <input type="checkbox" class="form-check-label" checked readonly>
                                    <span class="checkmark"></span>
                                </label>

                            </div>
                            <p><?php // echo $_item['customer_response'];
                                ?></p>
                        </div>
                        <?php
                        continue;
                    endif ?>
                    <?php
                    if ($_item['response_type'] == 'choice'):
                        ?>

                        <div class="answer">
                            <div class="form-check">
                                <!-- <input type="checkbox" class="form-check-label" checked readonly /><label class="form-check-label"><?php echo $_item['question_response_data']['label']; ?></label> -->
                                <label
                                    class="input-check-label"><?php echo $_item['question_response_data']['label']; ?>
                                    <input type="checkbox" class="form-check-label" checked readonly>
                                    <span class="checkmark"></span>
                                </label>
                            </div>
                            <p><?php //echo $_item['customer_response'];
                                ?></p>
                        </div>
                        <?php
                        continue;
                    endif; ?>

                    <?php
                    if ($_item['response_type'] == 'combotextadd'):

                        $combotextaddValues = array_filter(explode(',', $_item['customer_response']));
                        if (!is_array($combotextaddValues)) {
                            $combotextaddValues = [];
                        }

                        $combotextaddValues = implode(", ", $combotextaddValues);

                        if (trim($combotextaddValues) == '') {
                            $combotextaddValues = '- (None)';
                            $noneClass = 'no-answer';
                        }
                        ?>

                        <div class="answer">
                            <div>
                                <p class="answer-label"><?php echo $_item['question_response_data']['label']; ?></p>
                            </div>
                            <?php /* foreach ($combotextaddValues as $combotextValue) { ?>

                                         <p class="answer-label"><input type="text" value="<?=$combotextValue?>"></p>
                                        <?php } */ ?>
                            <p class="answer-label"><span class="<?= $noneClass ?>"><?= $combotextaddValues ?></span>
                            </p>
                        </div>
                        <?php
                        continue;
                    endif; ?>

                    <?php


                    if (trim($_item['customer_response']) == '') {

                        $_item['customer_response'] = '- (None)';
                        $noneClass = 'no-answer';
                    } else {
                    }
                    ?>

                    <div class="answer">
                        <p class="info-ele"><span
                                class="label"><?php echo $_item['question_response_data']['label']; ?></span> <span
                                class="<?= $noneClass ?>"><?php echo $_item['customer_response']; ?></span></p>

                    </div>


                    <?php endforeach;
                    ?>

                    <?php endforeach; ?>
                    <?php
                    if ($dividerElement) {
                        $dividerElement = false;
                        echo '</div>';
                    }
                    ?>
                </div>
            </div>
        </div>
    </div>
    <?php endif; ?>

    <style>
        body {
            /* font-family: "aktiv-grotesk", sans-serif !important; */
        }

        .custom-container {
            max-width: 600px !important;
        }

        @media (min-width: 768px) {
            .custom-container {
                max-width: 65% !important;
            }
        }

        label.form-check-label {
            width: inherit;
        }

        div.form-check {
            padding: 0px;
            padding-left: 1.5em;
            padding: 16px 20px;
        }

        .form-check .form-check-input {
            margin-left: -0.5em;
            margin-top: -4px;
        }

        .form-check-input:checked[type=radio] {
            background-image: url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='-4 -4 8 8'%3e%3ccircle r='2' fill='%23644B4F'/%3e%3c/svg%3e");
            background-size: 160% auto;
        }

        .form-check-input:checked {
            background-color: #fff;
            border-color: #644B4F;
        }

        label.form-check-label {
            margin: 0 30px !important;
            padding: 0px !important;
            font-weight: 500;
            font-size: 14px;
            display: block;
        }

        /* The container */
        .input-check-label {
            display: block;
            position: relative;
            padding-left: 30px;
            margin-bottom: 0px;
            cursor: pointer;
            -webkit-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;
            font-size: 14px;
            font-weight: 500;
        }

        /* Hide the browser's default checkbox */
        .input-check-label input {
            position: absolute;
            opacity: 0;
            cursor: pointer;
            height: 0;
            width: 0;
        }

        /* Create a custom checkbox */
        .checkmark {
            position: absolute;
            top: -2px;
            left: -8px;
            height: 25px;
            width: 25px;
            background-color: transparent;
            border: 1px solid #644B4F;
            border-radius: 100%;
        }

        /* On mouse-over, add a grey background color */
        .input-check-label:hover input ~ .checkmark {
            background-color: #ccc;
        }

        /* When the checkbox is checked, add a blue background */
        /* .input-check-label input:checked ~ .checkmark {
          background-color: #644B4F;
        } */

        /* Create the checkmark/indicator (hidden when not checked) */
        .checkmark:after {
            content: "";
            position: absolute;
            display: none;
        }

        /* Show the checkmark when checked */
        .input-check-label input:checked ~ .checkmark:after {
            display: block;
        }

        p#subhead {
            margin: 20px 0px;
        }

        /* Style the checkmark/indicator */
        .input-check-label .checkmark:after {
            /* left: 6px;
            top: 2px;
            width: 6px;
            height: 12px;
            border: solid white;
            border-width: 0 2px 2px 0;
          -webkit-transform: rotate(45deg);
          -ms-transform: rotate(45deg);
          transform: rotate(45deg); */
            left: 0;
            top: 0px;
            width: 23px;
            height: 23px;
            background: url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='-4 -4 8 8'%3e%3ccircle r='2' fill='%23644B4F'/%3e%3c/svg%3e");
            background-size: 160% auto;
            background-position: center;
            background-repeat: no-repeat;
        }

        .divider-div {
            padding-top: 20px;
        }

        .divider-div .divider {
            border-bottom: 1px solid #e2e2e2;
            margin-bottom: 30px;
            padding-left: 15px;
            padding-bottom: 30px;
            padding-right: 15px;
        }

        .divider p:empty {
            display: none;
        }

        .divider-div h5 {
            font-weight: bold;
            margin-bottom: 0px;
            font-size: 18px;
        }

        .divider-div p#subhead {
            margin: 20px 0px;
            font-size: 12px;
        }

        .divider p {
            margin-bottom: 5px;
        }

        p.answer-label {
            padding: 15px;
            border: 1px solid #202930;
            background: #fff;
            font-size: 15px;
            color: #202930;
        }

        .info-ele {
            margin-top: 10px;
            font-size: 15px;
        }

        .info-ele span {
            display: inline-block;
        }

        .info-ele span:first-child {
            font-weight: bold;
            margin-right: 10px;
        }
    </style>

