<?php
/*
$helperWP = $this->helper('\Ssmd\WPPages\Helper\Data');
$adminUrl = $helperWP->getAdminUrl();

*/?><!--

--><?php
/*
    // Customer Questions Responses
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();


    $json = $objectManager->get('\Magento\Framework\Json\Helper\Data');
    //$jsonEncode = $json->jsonEncode();
    $serializer = $objectManager->get('Magento\Framework\Serialize\SerializerInterface');
    $request = $objectManager->get('Magento\Framework\App\RequestInterface');
    $productId = $request->getParam('id');

    $product = $objectManager->get('Magento\Catalog\Model\ProductFactory')->create()->load($productId);
    $prodQA = $product->getData('product_ques_ans');

    if(!empty($prodQA))
    {
        $qaData = $serializer->unserialize($prodQA);
    }
    else
    {
        $qaData = [];
    }

    //echo "<pre>"; print_r($qaData); exit;


    if(!empty($qaData))
    {
        $ques=[];
        $totalQa=[];
        foreach ($qaData as $key => $value) {
            if($value['questions'] != "")
            {
                $ques['record_id'] = $value['record_id'];
                $ques['quest'] = $value['questions'];
                $ques['ans']   = $value['answers'];
            }
            $totalQa[] = $ques;
        }
        $opt = $json->jsonEncode($totalQa);
    }
    else
    {
        $totalQa = [];
        $opt = $json->jsonEncode($totalQa);
    }

*/?>

<!--<script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "*": {
                            "component": "Ssmd_ProductAdditionalContent/js/additionalcontent",
                            "admin_base_url": "<?php /*echo 'test' */?>",
                            "saved_answers": <?php /*echo 'test' */?>

                        }
                     }
                }
            }
        }
    </script>
-->

<script type="text/x-magento-init">
{
    "*": {
        "additionalcontent": {
            "ajaxUrlValue": "<?= 'test'?>"
        }
    }
}
</script>

