<?php /** @var \ParadoxLabs\Subscriptions\Block\Customer\Edit\Payment $block */ ?>
<?php /* @codingStandardsIgnoreFile */ ?>
<?php $activeCard = $block->getCard(); ?>
<?php $paymentMethodCodes = []; ?>

<fieldset class="fieldset">
    <legend class="legend"><span><?= $block->escapeHtml(__('Payment Information')) ?></span></legend><br>

    <?= $block->getChildHtml(); ?>

    <div class="field card required">
        <label class="label" for="tokenbase_id"><span><?= $block->escapeHtml(__('Payment Account')) ?></span></label>
        <div class="control">
            <select name="tokenbase_id" id="tokenbase_id" class="validate-select control-select" title="<?= $block->escapeHtmlAttr(__('Payment Account')) ?>">
                <?php /** @var \Magento\Vault\Api\Data\PaymentTokenInterface $card */ ?>
                <?php $cards = $block->getCustomerCards(); ?>
                <?php foreach ($cards as $card): ?>
                    <option value="<?= $block->escapeHtmlAttr($card->getPublicHash()); ?>"
                            data-method="<?= $card->getPaymentMethodCode() ?>"
                            data-offline="<?= $card instanceof \ParadoxLabs\Subscriptions\Model\OfflinePayment\Card ? '1' : '0' ?>"
                            <?php if ($activeCard !== null && $card->getPublicHash() === $activeCard->getPublicHash()): ?>selected="selected"<?php endif; ?>>
                        <?= $block->escapeHtml($block->getCardLabel($card)); ?>
                    </option>
                    <?php $paymentMethodCodes[$card->getPaymentMethodCode()] = 1; ?>
                <?php endforeach; ?>
            </select>
        </div>
    </div>

    <div class="payment-forms">
        <?php /** Output offline payment forms */ ?>
        <?php foreach ($block->getOfflinePaymentMethods() as $method): ?>
            <?php if ($method->getFormBlockType()): ?>
                <?= $block->getPaymentForm($method) ?>
            <?php endif; ?>
            <?php unset($paymentMethodCodes[$method->getCode()]); ?>
        <?php endforeach; ?>

        <?php /** Output TokenBase methods message */ ?>
        <?php foreach($block->getTokenbaseHelper()->getActiveMethods() as $methodCode): ?>
            <div class="field" id="payment_form_<?= $methodCode ?>" style="display: none">
                <p>
                    <?= $block->escapeHtml(__('To change your payment options, please go to')); ?>
                    <a href="<?= $block->escapeUrl($block->getUrl('customer/paymentinfo', ['method' => $methodCode])); ?>" target="_blank"><?= $block->escapeHtml(__('My Payment Data')); ?></a>.
                </p>
            </div>
            <?php unset($paymentMethodCodes[$methodCode]); ?>
        <?php endforeach; ?>

        <?php /** Output Vault methods message (any methods remaining) -- this will be wrong for any that implement their own custom mgmt page, but there's no means to avoid that */ ?>
        <?php foreach($paymentMethodCodes as $methodCode => $flag): ?>
            <div class="field" id="payment_form_<?= $methodCode ?>" style="display: none">
                <p>
                    <?= $block->escapeHtml(__('To manage your payment options, please go to')); ?>
                    <a href="<?= $block->escapeUrl($block->getUrl('vault/cards/listaction')); ?>" target="_blank"><?= $block->escapeHtml(__('Stored Payment Methods')); ?></a>.
                </p>
            </div>
        <?php endforeach; ?>
    </div>

    <?php if (empty($cards) && !empty($block->getTokenbaseHelper()->getActiveMethods())): ?>
        <div class="field" id="payment_form_<?= $method ?>" style="display: none">
            <p>
                <?= $block->escapeHtml(__('To change your payment options, please go to')); ?>
                <a href="<?= $block->escapeUrl($block->getUrl('customer/paymentinfo', ['method' => $method])); ?>" target="_blank"><?= $block->escapeHtml(__('My Payment Data')); ?></a>.
            </p>
        </div>
    <?php endif; ?>
</fieldset>
