<?php
/** @var \ParadoxLabs\Subscriptions\Block\Adminhtml\Subscription\View\Tab\Payment\Address $block */
// @codingStandardsIgnoreFile
?>
<div class="fieldset admin__fieldset" id="subscription_fieldset_billing" data-mage-init='{"subscriptionsAddressFields":{"addressSelector":"#billing_address_id"}}'>
    <?php $addresses = $block->getCustomer()->getAddresses(); ?>
    <?php $subscriptionAddress = $block->getSubscription()->getQuote()->getBillingAddress(); ?>
    <?php if (!empty($addresses)): ?>
        <div class="admin__field field region _required">
            <label class="admin__field-label label" for="billing_address_id"><span><?= $block->escapeHtml(__('Billing Address')) ?></span></label>
            <div class="admin__field-control control">
                <select id="billing_address_id" name="billing[address_id]" title="<?= $block->escapeHtmlAttr(__('Billing Address')) ?>" class="admin__control-select">
                    <option value=""><?= $block->escapeHtml(__('Enter below')) ?></option>
                    <?php /** @var \Magento\Customer\Api\Data\AddressInterface $address  */ ?>
                    <?php foreach ($addresses as $address): ?>
                        <option value="<?= (int)$address->getId(); ?>"<?php if ($this->helper(\ParadoxLabs\TokenBase\Helper\Address::class)->compareAddresses($address, $subscriptionAddress)): ?> selected="selected"<?php endif; ?>><?= $block->escapeHtml($block->getFormattedAddress($address, 'flat')); ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>
    <?php endif; ?>
    <div class="admin__field field toggle field-name-firstname _required">
        <label class="admin__field-label label" for="billing_firstname"><span><?= $block->escapeHtml(__('First Name')) ?></span></label>
        <div class="admin__field-control control">
            <input type="text" name="billing[firstname]" id="billing_firstname" title="<?= $block->escapeHtmlAttr(__('First Name')) ?>" value="<?= $block->escapeHtmlAttr($block->getAddress()->getFirstname()) ?>" class="admin__control-text <?= $block->escapeHtmlAttr($this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('firstname')) ?>" data-validate='{required:true}'>
        </div>
    </div>
    <div class="admin__field field toggle field-name-lastname _required">
        <label class="admin__field-label label" for="billing_lastname"><span><?= $block->escapeHtml(__('Last Name')) ?></span></label>
        <div class="admin__field-control control">
            <input type="text" name="billing[lastname]" id="billing_lastname" title="<?= $block->escapeHtmlAttr(__('Last Name')) ?>" value="<?= $block->escapeHtmlAttr($block->getAddress()->getLastname()) ?>" class="admin__control-text <?= $block->escapeHtmlAttr($this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('lastname')) ?>" data-validate='{required:true}'>
        </div>
    </div>
    <div class="admin__field field toggle company">
        <label class="admin__field-label label" for="billing_company"><span><?= $block->escapeHtml(__('Company')) ?></span></label>
        <div class="admin__field-control control">
            <input type="text" name="billing[company]" id="billing_company" title="<?= $block->escapeHtmlAttr(__('Company')) ?>" value="<?= $block->escapeHtmlAttr($block->getAddress()->getCompany()) ?>" class="admin__control-text <?= $block->escapeHtmlAttr($this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('company')) ?>">
        </div>
    </div>
    <?php $phoneValidation = $this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('telephone'); ?>
    <div class="admin__field field toggle telephone<?php if (strpos($phoneValidation, 'required') !== false): ?> _required<?php endif; ?>">
        <label class="admin__field-label label" for="billing_telephone"><span><?= $block->escapeHtml(__('Phone Number')) ?></span></label>
        <div class="admin__field-control control">
            <input type="text" name="billing[telephone]" value="<?= $block->escapeHtmlAttr($block->getAddress()->getTelephone()) ?>" title="<?= $block->escapeHtmlAttr(__('Phone Number')) ?>" class="admin__control-text <?= $block->escapeHtmlAttr($phoneValidation) ?>" id="billing_telephone"<?php if (strpos($phoneValidation, 'required') !== false): ?> data-validate='{required:true}'<?php endif; ?>>
        </div>
    </div>
    <?php $faxValidation = $this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('fax'); ?>
    <div class="admin__field field toggle fax<?php if (strpos($faxValidation, 'required') !== false): ?> _required<?php endif; ?>">
        <label class="admin__field-label label" for="billing_fax"><span><?= $block->escapeHtml(__('Fax Number')) ?></span></label>
        <div class="admin__field-control control">
            <input type="text" name="billing[fax]" value="<?= $block->escapeHtmlAttr($block->getAddress()->getFax()) ?>" title="<?= $block->escapeHtmlAttr(__('Fax Number')) ?>" class="admin__control-text <?= $block->escapeHtmlAttr($faxValidation) ?>" id="billing_fax"<?php if (strpos($faxValidation, 'required') !== false): ?> data-validate='{required:true}'<?php endif; ?>>
        </div>
    </div>
    <?php $_streetValidationClass = $block->escapeHtmlAttr($this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('street')); ?>
    <div class="admin__field field toggle street _required">
        <label for="billing_street" class="admin__field-label label"><span><?= $block->escapeHtml(__('Street')) ?></span></label>
        <div class="admin__field-control control">
            <input type="text" name="billing[street][]" value="<?= $block->escapeHtmlAttr($block->getStreetLine(1)) ?>" title="<?= $block->escapeHtmlAttr(__('Street Address')) ?>" id="billing_street" class="admin__control-text <?= $_streetValidationClass ?>" data-validate='{required:true}' />
            <div class="nested">
                <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                <?php for ($_i = 1, $_n = $this->helper(\Magento\Customer\Helper\Address::class)->getStreetLines(); $_i < $_n; $_i++): ?>
                    <?php $lineNo = ($_i+1); ?>
                    <div class="admin__field field additional">
                        <div class="admin__field-control control">
                            <input type="text" name="billing[street][]" value="<?= $block->escapeHtmlAttr($block->getStreetLine($lineNo)) ?>" title="<?= $block->escapeHtmlAttr(__('Street Address %1', $lineNo)) ?>" id="billing_street_<?= $lineNo ?>" class="admin__control-text <?= $_streetValidationClass ?>">
                        </div>
                    </div>
                <?php endfor; ?>
            </div>
        </div>
    </div>
    <div class="admin__field field toggle city _required">
        <label class="admin__field-label label" for="billing_city"><span><?= $block->escapeHtml(__('City')) ?></span></label>
        <div class="admin__field-control control">
            <input type="text" name="billing[city]" value="<?= $block->escapeHtmlAttr($block->getAddress()->getCity()) ?>" title="<?= $block->escapeHtmlAttr(__('City')) ?>" class="admin__control-text <?= $block->escapeHtmlAttr($this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('city')) ?>" id="billing_city" data-validate='{required:true}'>
        </div>
    </div>
    <div class="admin__field field toggle region _required">
        <label class="admin__field-label label" for="billing_region-id"><span><?= $block->escapeHtml(__('State/Province')) ?></span></label>
        <div class="admin__field-control control">
            <select id="billing_region-id" name="billing[region_id]" title="<?= $block->escapeHtmlAttr(__('State/Province')) ?>" class="admin__control-select validate-select" <?=(!$block->getConfig('general/region/display_all')) ? ' disabled="disabled"' : '';?>>
                <option value=""><?= $block->escapeHtml(__('Please select a region, state or province.')) ?></option>
            </select>
            <input type="text" id="billing_region" name="billing[region]" value="<?= $block->escapeHtmlAttr($block->getAddress()->getRegion() instanceof \Magento\Customer\Api\Data\RegionInterface ? $block->getAddress()->getRegion()->getRegion() : $block->getAddress()->getRegion()) ?>"  title="<?= $block->escapeHtmlAttr(__('State/Province')) ?>" class="admin__control-text <?= $block->escapeHtmlAttr($this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('region')) ?>"<?=(!$block->getConfig('general/region/display_all')) ? ' disabled="disabled"' : '';?>/>
        </div>
    </div>
    <div class="admin__field field toggle zip _required">
        <label class="admin__field-label label" for="billing_zip"><span><?= $block->escapeHtml(__('Zip/Postal Code')) ?></span></label>
        <div class="admin__field-control control">
            <input type="text" name="billing[postcode]" value="<?= $block->escapeHtmlAttr($block->getAddress()->getPostcode()) ?>" title="<?= $block->escapeHtmlAttr(__('Zip/Postal Code')) ?>" id="billing_zip" class="admin__control-text validate-zip-international <?= $block->escapeHtmlAttr($this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('postcode')) ?>">
        </div>
    </div>
    <div class="admin__field field toggle country _required">
        <label class="admin__field-label label" for="billing_country"><span><?= $block->escapeHtml(__('Country')) ?></span></label>
        <div class="admin__field-control control">
            <?= str_replace('class="', 'class="admin__control-select ', $block->getCountryHtmlSelect($block->getAddress()->getCountryId(), 'billing[country_id]', 'billing_country')) ?>
        </div>
    </div>
    <script type="text/javascript">
        //<![CDATA[
        <?php /* @see Magento\Customer\Block\Adminhtml\Edit\Renderer\Region::render() */ ?>
        require(["prototype", "mage/adminhtml/form"], function(){
            jQuery("#billing_region-id").attr("defaultValue", "<?= (int)$block->getAddress()->getRegionId() ?>");
            new RegionUpdater("billing_country", "billing_region", "billing_region-id", <?= $this->helper(\Magento\Directory\Helper\Data::class)->getRegionJson() ?> );
        });
        //]]>
    </script>
</div>
