<?php

$medicalHistoryArr = $block->getCustomerMedicalHistory();

?>

<div class="fieldset-wrapper-title" data-bind="attr: {tabindex: !collapsible ? -1 : 0,
               'data-state-collapsible': collapsible ? opened() ? 'open' : 'closed' : null}, click: toggleOpened, keyboard: {13: toggleOpened}" tabindex="-1">

        <strong data-bind="css: {'admin__collapsible-title': collapsible,
                      title: !collapsible,
                      '_changed': changed,
                      '_loading': loading,
                      '_error': error}" class="title">
            <span data-bind="i18n: label">Medical History</span>
            <!-- ko if: collapsible --><!-- /ko -->
        </strong>
</div>

<?php 
//if($medicalHistoryArr)
foreach ($medicalHistoryArr as $medicalHistory) { ?>
<div class="admin__field" data-bind="css: $data.additionalClasses, attr: {'data-index': index}, visible: visible" data-index="prefix">
    <div class="admin__field-label" data-bind="visible: $data.labelVisible">
        <!-- ko if: $data.label --><label data-bind="attr: {for: uid}" for="YF5RSNF">
            <span data-bind="attr: {'data-config-scope': $data.scopeLabel}, i18n: label"></span>
        </label><!-- /ko -->
    </div>
    <div class="admin__field-control" data-bind="css: {'_with-tooltip': $data.tooltip, '_with-reset': $data.showFallbackReset &amp;&amp; $data.isDifferedFromDefault}">
        <span id="current_score_credit"><b><?php echo $medicalHistory['question_text']?></b> : <?php echo $medicalHistory['response']?></span>
        <span>&nbsp;&nbsp;&nbsp;&nbsp;</span>
        <span><a onclick="return showPopupSlide('<?php echo $medicalHistory['id'] ?>')" href="#">Edit</a></span>
    </div>
</div>
<?php }?>


<script>
    
    // Opening a SlideOut
    function showPopupSlide(id)
    {
        var viewUrl = '<?php echo $this->getUrl('backend/medical/view/') ?>id/'+id;
        popupSlider.open(viewUrl,id);
    }

</script>


<script>
   require([
       "jquery",
       "Magento_Ui/js/modal/modal",
       'mage/backend/notification',
       "prototype"
   ], function(jQuery, modal, notification) {

//<![CDATA[
       Window.keepMultiModalWindow = true;
       var popupSlider = {
           overlayShowEffectOptions : null,
           overlayHideEffectOptions : null,
           modal: null,
           open : function(viewUrl, elementId) {
               if (viewUrl && elementId) {
                   jQuery.ajax({
                       url: viewUrl,
                       data: {
                           id: elementId
                       },
                       showLoader: true,
                       dataType: 'html',
                       success: function(data, textStatus, transport) {
                           this.openDialogWindow(data, elementId);
                       }.bind(this)
                   });
               }
           },
           openDialogWindow : function(data, elementId) {
               var self = this;
               if (this.modal) {
                   this.modal.html(jQuery(data).html());
               } else {
                   this.modal = jQuery(data).modal({
                       title: '<?= /* @escapeNotVerified */ __('Edit Medical History'); ?>',
                       modalClass: 'magento',
                       type: 'slide',
                       firedElementId: elementId,
                       buttons: [{
                           text: jQuery.mage.__('Close'),
                           class: 'action- scalable back',
                           click: function () {
                               self.closeDialogWindow(this);
                           }
                       }],
                       close: function () {
                           self.closeDialogWindow(this);
                       }
                   });
               }
               this.modal.modal('openModal');
           },
           closeDialogWindow : function(dialogWindow) {

               jQuery('body').trigger('processStop');
               dialogWindow.closeModal();
               Windows.overlayShowEffectOptions = this.overlayShowEffectOptions;
               Windows.overlayHideEffectOptions = this.overlayHideEffectOptions;
           }
       };

       window.popupSlider = popupSlider;
//]]>
   });
</script>



