<?php
$baseurl        = $block->getBaseUrl();
$customerId     = $block->getCustomerId();
?>

<div class="fieldset-wrapper-title" data-bind="attr: {tabindex: !collapsible ? -1 : 0,
               'data-state-collapsible': collapsible ? opened() ? 'open' : 'closed' : null}, click: toggleOpened, keyboard: {13: toggleOpened}" tabindex="-1">

    <strong data-bind="css: {'admin__collapsible-title': collapsible,
                  title: !collapsible,
                  '_changed': changed,
                  '_loading': loading,
                  '_error': error}" class="title">
        <span data-bind="i18n: label">Customer Reset Password</span>
        <!-- ko if: collapsible --><!-- /ko -->
    </strong>
</div>
<div class="admin__field" data-bind="css: $data.additionalClasses, attr: {'data-index': index}, visible: visible" data-index="prefix">
    <div class="admin__field-label" data-bind="visible: $data.labelVisible">
        <!-- ko if: $data.label --><label data-bind="attr: {for: uid}" for="">
            <span data-bind="attr: {'data-config-scope': $data.scopeLabel}, i18n: label"></span>
        </label><!-- /ko -->
    </div>

</div>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
<style>
    /*  .password-container{
    width: 400px;
    position: relative;
  }
  .password-container input[type="password"],
  .password-container input[type="text"]{
    width: 100%;
    padding: 12px 36px 12px 12px;
    box-sizing: border-box;
  }
  .fa-eye{
    position: absolute;
    top: 28%;
    right: 4%;
    cursor: pointer;
    color: lightgray;
  }*/
    .fa-eye{
        cursor: pointer;
    }
    .fa-eye-slash{
        cursor: pointer;
    }
</style>
<script>
    require(['jquery'], function ($) {

        $(document).on('click', '.toggle-password', function() {

            $(this).toggleClass("fa-eye fa-eye-slash");

            var input = $("#password");
            input.attr('type') === 'password' ? input.attr('type','text') : input.attr('type','password')
        });
    });

</script>
<form name="resetpass" method="POST" action="<?php echo $this->getUrl('customer/index/resetPassword') ?>">
    <div>
        <div style="padding-bottom: 10px;">
            <span>Enter New Password</span><span>&nbsp;&nbsp;</span><span><input type="password" name="reset_password" placeholder="Password..." id="password">
              <i class="fa-solid fa-eye toggle-password" id="eye"></i></span>
            <!-- <div class="password-container"> -->

            <!-- </div> -->
        </div>
        <div style="padding-bottom: 10px;">

            <input type="hidden" name="form_key" id="form_key" value="<?php echo $block->getFormKey() ?>"/>
            <input type="hidden" name="customer_id" id="customer_id" value="<?php echo $block->getCustomerId() ?>"/>
        </div>

        <div style="padding-bottom: 10px;">
            <span><button type="submit" class="action submit primary" id="reset_password_button">
                <span><?= $block->escapeHtml(__('Change Password')) ?></span>
            </button></span>

        </div>
    </div>
</form>
